- name: check if a list of services state
  hosts: all 
  tasks:
  - name: check all services
    service_facts:
    
  - name: display the state of the wanted services
    debug:
      msg: 
        - |
          name: {{ item }}
          state: {{ ansible_facts.services[item].state }}
          status: {{ ansible_facts.services[item].status }}
    loop:
      - sshd
      - httpd
      - nginx
